---
- name: Setup gamepc
  hosts: gamepc
  gather_facts: false
  tasks:
    # The script in the README starts this, *however* I've had issues where it doesn't persist on reboot
    - name: Ensure WinRM starts on boot
      ansible.windows.win_service:
        name: WinRM
        state: started
        start_mode: auto
      tags: winrm
    - name: Set computer hostname
      ansible.windows.win_hostname:
        name: "{{ inventory_hostname }}"
      tags: hostname
    # RDP snippets from: https://oneuptime.com/blog/post/2026-02-21-how-to-use-ansible-to-configure-windows-remote-desktop/view
    - name: Configure Remote Desktop
      tags: rdp
      # Forces the default user (me) to login when the machine powers on
      block:
        - name: Enable Remote Desktop via registry
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
            name: fDenyTSConnections
            data: 0
            type: dword
            state: present
        - name: Enable Network Level Authentication (NLA)
          ansible.windows.win_regedit:
            path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
            name: UserAuthentication
            data: 1
            type: dword
            state: present
        - name: Allow RDP through Windows Firewall
          ansible.windows.win_powershell:
            script: |
              Set-NetFirewallRule -DisplayGroup "Remote Desktop" -Enabled True -Profile Any
          changed_when: false
        - name: Start Remote Desktop Services
          ansible.windows.win_service:
            name: TermService
            state: started
            start_mode: auto
    - name: Enable autologin
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        type: String
      loop:
        - { name: AutoAdminLogon, data: "1" }
        - { name: DefaultUserName, data: "{{ ansible_user }}" }
        - { name: DefaultPassword, data: "{{ ansible_password }}" }
      no_log: true
      tags: autologin
    # Enforces preferred power settings
    - name: Set 24-hour time format
      ansible.windows.win_regedit:
        path: HKCU:\Control Panel\International
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        type: String
      loop:
        - { name: sTimeFormat, data: "HH:mm:ss" }
        - { name: sShortTime, data: "HH:mm" }
      tags: time
    - name: Set timezone to America/New_York
      ansible.windows.win_timezone:
        timezone: Eastern Standard Time
      tags: time
    - name: Set power plan to high performance
      community.windows.win_power_plan:
        name: High performance
      tags: power
    - name: Disable sleep and hibernation
      ansible.windows.win_powershell:
        script: |
          powercfg /change standby-timeout-ac 0
          powercfg /change standby-timeout-dc 0
          powercfg /change hibernate-timeout-ac 0
          powercfg /change hibernate-timeout-dc 0
          powercfg /hibernate off
      # I was having issues with this command hanging
      timeout: 20
      changed_when: false
      tags: power
    - name: Install apps
      chocolatey.chocolatey.win_chocolatey:
        name:
          - dotnet-desktopruntime
          - vcredist-all
          - directx
          - steam
          - epicgameslauncher
          - goggalaxy
          - nvidia-display-driver
          - ludusavi
          - sunshine
          - kodi
          - magpie
        state: present
    # Playnite installation seems to succeed despite throwing errors
    - name: Install Playnite
      chocolatey.chocolatey.win_chocolatey:
        name: playnite
        state: present
      failed_when: false
    - name: Install apps (ignore checksums)
      chocolatey.chocolatey.win_chocolatey:
        name:
          - ea-app
        state: present
        ignore_checksums: true
    # Replace explorer.exe with Playnite as the shell
    # Changing between apps would sometimes trigger it, making it hard to get back with a controller.
    - name: Set Playnite Fullscreen as the Windows shell
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: Shell
        data: '"%LOCALAPPDATA%\Playnite\Playnite.FullscreenApp.exe"'
        type: ExpandString
      tags: shell
    # Store SMB credentials in Credential Manager
    #
    # This was needed to have it automatically mount on reboot. I was a bit confused by this myself.
    # The WinRM session doesn't have the ability so store this, but using "runas" allows to to access DPAPI data.
    #
    # This is done a bit cyclically.  These credentials are stored to be used later on login, where it can unlock any SMB shares, which are saved by the server.
    - name: Store SMB credentials
      changed_when: false
      ansible.windows.win_credential:
        name: "{{ smb_server }}"
        type: domain_password
        username: gamepc
        secret: "{{ smb_password }}"
        state: present
      become: true
      become_method: ansible.builtin.runas
      become_user: "{{ ansible_user }}"
      vars:
        ansible_become_password: "{{ ansible_password }}"
      no_log: true
      tags: smb
    # Mount & map ludusavi drive
    # This should mount it instantly & persist on reboot
    - name: Map Ludusavi backup share
      ansible.windows.win_mapped_drive:
        letter: Z
        path: "\\\\{{ smb_server }}\\ludusavi"
        username: "gamepc"
        password: "{{ smb_password }}"
        state: present
      no_log: true
      tags: smb
    - name: Map GamePC share
      ansible.windows.win_mapped_drive:
        letter: Y
        path: "\\\\{{ smb_server }}\\gamepc-share"
        username: "gamepc"
        password: "{{ smb_password }}"
        state: present
      no_log: true
      tags: smb
    - name: Run Win11Debloat with args
      ansible.windows.win_powershell:
        script: |
          & ([scriptblock]::Create((irm "https://debloat.raphi.re/"))) -Silent -RunDefaults -DisableLocationServices -RemoveApps -Apps "Microsoft.OneDrive" -RemoveCommApps
      changed_when: false
