---
# Replace explorer.exe with Kodi as the shell
- name: Set Kodi as the Windows shell
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: Shell
    data: '"C:\Program Files\Kodi\kodi.exe"'
    type: String
# Originally, I had Playnite start on boot + cec-tray.exe
# However, Kodi launches its own cec instance on start, and has the ability to configure settings in its interface
# So now the workflow is PC boot -> Kodi -> Playnite
- name: Add Playnite launcher to Kodi favorites
  ansible.windows.win_copy:
    dest: "C:\\Users\\{{ ansible_user }}\\AppData\\Roaming\\Kodi\\userdata\\favourites.xml"
    content: |
      <favourites>
        <favourite name="Playnite">System.Exec("C:\Users\{{ ansible_user }}\AppData\Local\Playnite\Playnite.FullscreenApp.exe")</favourite>
      </favourites>
